### ISSUE TITLE
Module calls remote URL to generate QR code?

### ISSUE THREAD

**Issue by saibotsivad** [modood/make-qrcode#1]
It appears that this module does not generate the QR code natively, but instead calls a remote URL which generates the QR code image.

This should be documented clearly, so that people are aware of the security risks of using this module for private data.

**Comment by saibotsivad** [comment]
@modood could you also push a patch version to npm? I often just look at the npm readme instead of the github readme, so it'd be good to have that visible there as well. Thanks!

**Comment by modood** [comment]
@saibotsivad okay..

**Comment by saibotsivad** [comment]
Thank you!
